name: Build and Deploy
'on':
  push:
    tags:
      - '*'
    branches:
      - main
      - development
      - refactor-quick-docs
jobs:
  dockerize_stage:
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'|| github.ref == 'refs/heads/refactor-quick-docs' || github.ref == 'refs/heads/development') && (github.event_name == 'push')
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    name: 🐳 Dockerize Stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download UI Image
        run: |
          docker pull ghcr.io/gofr-dev/website:workflow-package

      - name: Build and Push Image Stage
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          file: ./docs/Dockerfile
          tags: gcr.io/zs-products/gofr-web:${{ github.sha }}

      - id: output-image
        run: echo "image=`echo gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}`" >> "$GITHUB_OUTPUT"

  stage_deployment:
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Stage
    if: (github.ref == 'refs/heads/development')
    needs: dockerize_stage
    container:
      image: ghcr.io/zopsmart/gha-images:deployments-0.1.3
      options: --rm
    env:
      image: ${{needs.dockerize_stage.outputs.image}}

    steps:
      - name: Authorize to GCP service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}

      - name: Set GCloud Project and Fetch Cluster Credentials
        run:
          gcloud container clusters get-credentials products-cluster --zone=us-central1 --project=zs-products

      - name: Update Deployment Image
        run: kubectl set image deployment/gofr-web gofr-web=${{ env.image }} --namespace gofr-stage

  check-tag:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v')}}
    outputs:
      tag_exists: ${{ steps.tag-check.outputs.tag_exists }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authorize to GCP service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCR_KEY }}

      - name: Check if tag exists
        id: tag-check
        run: |
          if gcloud container images describe gcr.io/zs-products/gofr-web:${{ github.sha }} 2>/dev/null; then
              echo "tag_exists=true" >> "$GITHUB_OUTPUT"
          else
              echo "tag_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Print commit has value
        run: |
          echo "${{ github.sha }}"

      - name: Print tag_exists value
        run: |
          echo "${{ steps.tag-check.outputs.tag_exists }}"

  dockerize_prod:
    runs-on: ubuntu-latest
    needs: check-tag
    name: 🐳 Dockerize Prod
    if: ${{ needs.check-tag.outputs.tag_exists == 'true' }}
    outputs:
      image: ${{ steps.output-image.outputs.image }}

    steps:
      - name: Extract Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}

      - name: Re tag and Push Docker Image to GCR
        run: |
          docker pull gcr.io/zs-products/gofr-web:${{ github.sha }}
          docker tag gcr.io/zs-products/gofr-web:${{ github.sha }} gcr.io/zs-products/gofr-web:${{ env.RELEASE_VERSION }}
          docker push gcr.io/zs-products/gofr-web:${{ env.RELEASE_VERSION }}

      - id: output-image
        run: echo "image=`echo gcr.io/zs-products/gofr-web:${{ env.RELEASE_VERSION }}`" >> "$GITHUB_OUTPUT"

  prod_deployment:
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Prod
    needs: dockerize_prod
    container:
      image: ghcr.io/zopsmart/gha-images:deployments-0.1.3
      options: --rm
    env:
      image: ${{needs.dockerize_prod.outputs.image}}
    steps:
      - name: Extract Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Authorize to GCP service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}

      - name: Set GCloud Project and Fetch Cluster Credentials
        run: gcloud container clusters get-credentials products-cluster --zone=us-central1 --project=zs-products

      - name: Update Deployment Image
        run: kubectl set image deployment/gofr-web gofr-web=${{ env.image }} --namespace gofr